### ISSUE TITLE
Match verse lists if separated by semicolons

### ISSUE THREAD

**Issue by cguldner** [cguldner/BiblePreviewer#28]
Joel 2:4; 9-10 is an example

**Comment by timbze** [comment]
@cguldner You might like to look into using [Bible-Passage-Reference-Parser](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser). The FOSS app AndBible implemented it for user's note cross-references [here](https://github.com/AndBible/and-bible/pull/981)
